kind: Pod                         
apiVersion: v1                  
metadata:                         
  name: runtimeerr                 
spec:   
  imagePullSecrets:
        - name: docker-credentials                          
  containers:                     
    - name: main                                   
      image: adamtravis/wezvatechspringboot:sep24
