kind: Pod                         
apiVersion: v1                  
metadata:                         
  name: imagepull                  
spec:   
  imagePullSecrets:
        - name: docker-credentials                          
  containers:                     
    - name: main                                   
      image: adamtravis/wezvatechspringboot:release  
